### ISSUE TITLE
std::out_of_range

### ISSUE THREAD

**Issue by davidecarlson** [applevir/STEAK#2]
Hi STEAK devs,
I'm having an issue using your software that I'm hoping you can help with.  I compiled STEAK successfully and ran it on the test data without issue.  Now when I try to use my own data, I'm having problems.  First, although I used the suggested procedure to interleave and sort my paired fastq data, I'm still receiving the following message:

> Paired-ends files must be sorted by name.
More importantly, when I use single end data (to avoid the paired end issue), I get the following error:

> terminate called after throwing an instance of 'std::out_of_range'
>   what():  basic_string::substr
> 
> ===================================================================================
> =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
> =   PID 49131 RUNNING AT hal9000
> =   EXIT CODE: 134
> =   CLEANING UP REMAINING PROCESSES
> =   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
> ===================================================================================

Here is the command I'm trying to run:
mpirun -np 4 steak --input 2338_A_R1.fastq --TE-reference /path/to/my/repeat/lib/allRepeats.lib.fa

Am I doing something wrong? 
Thanks!
Dave

**Comment by applevir** [comment]
Hi Dave,

Thanks for your question. It looks to me like the issue might be with your TE-reference file. Is there more than one sequence in your FASTA? Just to clarify, STEAK only accepts FASTA files with a single sequence. Unfortunately, STEAK does not work with multiple reference sequences at this time.

Kind regards,
Cindy

**Comment by davidecarlson** [comment]
Hi Cindy,
Thanks for your response!  I was indeed using a TE reference file with more than one sequence.  I just tried again using a single TE sequence this time:

> mpirun -np 16 steak --input 2338_A_R1.fastq --TE-reference copia.fa

And I'm getting an error similar to what I was seeing before:  

> terminate called after throwing an instance of 'std::out_of_range'
>   what():  basic_string::substr
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  basic_string::substr
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  basic_string::substr
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  basic_string::substr
> -------------------------------------------------------
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.
> -------------------------------------------------------
> --------------------------------------------------------------------------
> mpirun noticed that process rank 0 with PID 0 on node hal9000 exited on signal 6 (Aborted).
> --------------------------------------------------------------------------

Any ideas what might be going on?
Thanks!
Dave

**Comment by applevir** [comment]
Apologies for the tardy reply.  Here's a possible explanation.
An out of range error often tends to be because of discrepancy between the read size and the bait size, make sure that the bait is not too large for the read size that you have. In paired mode this sort of error can be due to unsorted reads but as singletons there should not be an issue...
