### ISSUE TITLE
signal 11 segmentation fault during piping into steak

### ISSUE THREAD

**Issue by kimsjune** [applevir/STEAK#4]
Hello,

I am trying to pipe paired, name-sorted bam as input for steak using biobambam2. My command is : 

bamcollate2  filename=three_sortedbyname.bam outputformat=sam | steak --pipe --TE-reference ERV.fa --paired --aligned --output three_ERV

When I run this command, I am faced with the following error:

[gra-login1:22427:0] Caught signal 11 (Segmentation fault)
==== backtrace ====
 2 0x000000000005723c mxm_handle_error()  /tmp/mxm_local_copy/mxm-3.5.3094/src/mxm/util/debug/debug.c:641
 3 0x00000000000573ac mxm_error_signal_handler()  /tmp/mxm_local_copy/mxm-3.5.3094/src/mxm/util/debug/debug.c:616
 4 0x0000000000033280 killpg()  ??:0
 5 0x0000000000425c95 _ZN7SAMData3setERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE()  ??:0
 6 0x000000000041554f _ZN8bam_pipe8get_readER4Read()  ??:0
 7 0x00000000004346f8 main()  ??:0
 8 0x00000000000202e0 __libc_start_main()  ??:0
 9 0x000000000040ef2a _start()  /tmp/nix-build-glibc-2.24.drv-0/glibc-2.24/csu/../sysdeps/x86_64/start.S:120
===================
Segmentation fault

The first part of the command before | runs fine as sam file is outputted. 

I would appreciate any help. Thank you!

**Comment by applevir** [comment]
Apologies for the late reply. This can sometimes come up if you've compiled STEAK using a different version from the one that MPI on your computer/cluster was compiled with. Check if you compile can compile STEAK with another available compiler and try again. We've gotten this question a few times now via e-mail and it seems to be the case from what we've seen.
