### ISSUE TITLE
Can't work with paired-end data

### ISSUE THREAD

**Issue by foriin** [applevir/STEAK#5]
Hey
I'm trying to run steak with a paired-end fastq, but I always get 'Paired-ends files must be sorted by name.' error, though I made an interleaved file from two and sorted it by id. Could you please help?
Thanks

**Comment by santaci** [comment]
Hi forlin, Could you by any chance provide a short example of your interleaved file? Sometimes the IDs can be problematic depending on how they are formatted.

**Comment by santaci** [comment]
Hi forlin, Could you by any chance provide a short example of your interleaved file? Sometimes the IDs can be problematic depending on how they are formatted.
